### ISSUE TITLE
No "Your Turn ..." message is generated for character with higest initiative value in certain systems

### ISSUE THREAD

**Issue by MNielson** [EndlessFractal/yourTurn#2] opened 2023-07-07 13:12 UTC
In certain systems, such as Exalted Essence, the character with the highest initiative value does not automatically go first during later rounds of combat, or even during the first round of combat.

As such, systems like this sometimes implement a button that sets a character as "active" as opposed to that state being handled by initative value alone.
For most characters in the tracker, this works with Your Turn:

Expected Behavior
Clicking this to set the character as active
![image](https://github.com/EndlessFractal/yourTurn/assets/23503856/9e2e41cd-5827-4f60-99cd-9862196ffeea)

correctly announces that characters turn
![image](https://github.com/EndlessFractal/yourTurn/assets/23503856/db4c01e6-875d-46d8-909a-52f4617f58d5)

Incorrect Behavior
Clicking the same button for the character with the higest initiative value 
![image](https://github.com/EndlessFractal/yourTurn/assets/23503856/13da7a97-af23-452a-85d9-1563a1767e75)

does not create any message
![image](https://github.com/EndlessFractal/yourTurn/assets/23503856/71063b0b-af51-4ad9-b945-c00e2c63299d)

**Comment by EndlessFractal** [comment] 2024-02-10 00:31
Closing this as a duplicate of #1

**Closed as completed by EndlessFractal** 2024-02-10 00:31 UTC
Labels: enhancement, help wanted
